nav = new SceneNavigator([
 "startup",
 "de_00_arrival",
 "de_00_identity",
 "de_00_exam_room_01",
 "en_00_exam_room_01",
 "de_00_exam_room_02",
 "en_00_exam_room_02",
 "de_00_exam_room_03",
 "en_00_exam_room_03",
 "de_00_post_exam",
 "en_00_post_exam",
 "de_00_itharkael_free_time",
 "en_00_itharkael_free_time",
 "de_00_great_hall",
 "en_00_great_hall",
 "de_00_demo_end",
 "en_00_demo_end",
 "de_00_character_creation"
]);
stats = {
 "choice_title": "Ananthara: The Lost Fragments",
 "name": "",
 "language": "",
 "race": "",
 "race_image": "",
 "race_lore": "",
 "race_lens": "",
 "homeland": "",
 "homeland_image": "",
 "homeland_lore": "",
 "homeland_lens": "",
 "personal_history": "",
 "personal_history_full": "",
 "seeker_reason": "",
 "seeker_reason_full": "",
 "campaign_route_01": "",
 "personal_quest_id": "",
 "personal_quest_stage": "unassigned",
 "personal_quest_discovery_01": "",
 "personal_quest_discovery_02": "",
 "corvus_personal_disclosure": "",
 "personal_quest_log_visible": "false",
 "personal_quest_log_title": "",
 "personal_quest_log_objective": "",
 "personal_quest_log_item_01": "",
 "personal_quest_log_item_02": "",
 "personal_quest_log_question_01": "",
 "personal_quest_log_question_02": "",
 "personal_room2_vision_seen": "false",
 "personal_room2_clue_discovered": "false",
 "missing_mural_connection": "false",
 "lost_memory_sand_ruin": "false",
 "affliction_veil_connection": "false",
 "room2_seen_divine_light": "false",
 "room2_seen_creation_lines": "false",
 "room2_seen_closed_hands": "false",
 "room2_seen_veil": "false",
 "missing_room2_name_or_relationship": "",
 "missing_room2_symbol_or_trait": "",
 "missing_person_relationship": "",
 "missing_connection_memory": "",
 "quest_exam_status": "inactive",
 "quest_exam_objective": "",
 "quest_exam_room_02_status": "locked",
 "quest_exam_room_02_objective": "",
 "quest_exam_room_02_discovery_01": "",
 "quest_exam_room_02_discovery_02": "",
 "quest_exam_room_02_discovery_03": "",
 "quest_exam_room_03_status": "locked",
 "quest_exam_room_03_objective": "",
 "quest_exam_room_03_discovery_01": "",
 "quest_exam_room_03_discovery_02": "",
 "quest_exam_room_03_discovery_03": "",
 "room3_light_pattern_understood": "false",
 "room3_self_as_light_understood": "false",
 "room3_light_carried_through_darkness": "false",
 "room3_pedestal_activated": "false",
 "room3_chronicles_replica_manifested": "false",
 "room3_personal_question": "",
 "room3_replica_choice": "",
 "knowledge_truth": "0",
 "knowledge_guard": "0",
 "knowledge_gift": "0",
 "knowledge_self": "0",
 "knowledge_conviction_initial": "",
 "missing_person_name": "",
 "lost_memory_sand_ruin_discovered_via_replica": "false",
 "lost_memory_tehand_inscription": "false",
 "lost_memory_tehand_translation_known": "false",
 "affliction_shared_source_known": "false",
 "exam_room_02_mural_restored": "false",
 "room2_seeker_thalithara_theory": "false",
 "exam_room_02_mural_examined": "false",
 "room2_light_source_observed": "false",
 "room2_hidden_light_network_examined": "false",
 "room2_hidden_book_revealed": "false",
 "exam_room_02_complete": "false",
 "room2_light_stage": "0",
 "room2_examined_seams": "false",
 "room2_examined_breaks": "false",
 "room2_examined_controls": "false",
 "room2_examined_magic": "false",
 "room2_initial_investigations": "0",
 "room2_detail_count": "0",
 "echo_exam_room_02": "",
 "quest_exam_room_01_visible": "false",
 "quest_exam_room_01_status": "inactive",
 "quest_exam_room_01_objective": "",
 "quest_exam_room_01_discovery_01": "",
 "quest_exam_room_01_discovery_02": "",
 "quest_exam_room_01_discovery_03": "",
 "quest_exam_room_01_item_01": "",
 "quest_exam_room_01_note_01": "",
 "quest_exam_room_01_note_02": "",
 "exam_room_01_first_block": "",
 "exam_room_01_scroll_done": "false",
 "exam_room_01_room_done": "false",
 "exam_room_01_room_thal_used": "false",
 "exam_room_01_danger_known": "false",
 "exam_room_01_hidden_revealed": "false",
 "exam_room_01_hidden_method": "",
 "exam_room_01_recitation_found": "false",
 "exam_room_01_recitation_used": "false",
 "exam_room_01_sequence_known": "false",
 "exam_room_01_puzzle_line": "1",
 "exam_room_01_scroll_disposition": "",
 "exam_room_01_copy_first": "",
 "exam_room_01_copy_second": "",
 "exam_room_01_l1_crown": "false",
 "exam_room_01_l1_water": "false",
 "exam_room_01_l1_sun": "false",
 "exam_room_01_l2_water": "false",
 "exam_room_01_l2_sun": "false",
 "exam_room_01_l2_eye": "false",
 "exam_room_01_l3_crown": "false",
 "exam_room_01_l3_eye": "false",
 "exam_room_01_l3_water": "false",
 "exam_room_01_l4_crown": "false",
 "exam_room_01_l4_blade": "false",
 "exam_room_01_l4_sun": "false",
 "thal_type": "",
 "thal_description": "",
 "thal_passive": "",
 "thal_growth": "",
 "thal_calling": "",
 "thal_archetype": "",
 "thal_resonance": "",
 "thal_manifestation": "",
 "thal_calling_description": "",
 "thal_affinity": "",
 "thal_resonance_description": "",
 "thal_manifestation_description": "",
 "guild_rank": "Initiate Seeker",
 "current_stability": "Balanced",
 "origin": "",
 "origin_lens": "",
 "echo_origin": "",
 "oracle_card": "",
 "oracle_card_title_de": "",
 "oracle_card_title_en": "",
 "oracle_card_text_de": "",
 "oracle_card_text_en": "",
 "oracle_card_full_de": "",
 "oracle_card_full_en": "",
 "oracle_card_image": "",
 "oracle_card_drawn": "false",
 "prophecy_01_card": "",
 "prophecy_01": "",
 "prophecy_01_de": "",
 "prophecy_01_en": "",
 "prophecy_01_revealed": "false",
 "neugier": "0",
 "offenheit": "0",
 "innere_balance": "0",
 "wyld_vertrauen": "0",
 "verbundenheit": "0",
 "resonanz": "0",
 "authentizitaet": "0",
 "vorsicht": "0",
 "sacred_wylds_interest": "false",
 "asked_about_food": "false",
 "interested_in_dance": "false",
 "veild_interest": "false",
 "ritual_participation": "false",
 "echo_meditation": "false",
 "reflection_path": "false",
 "reflection_connection": "false",
 "reflection_uncertain": "false",
 "ritual_focus": "",
 "first_ritual_station": "",
 "loslassen_choice": "",
 "wunsch_choice": "",
 "dank_choice": "",
 "echo_intro": "",
 "echo_wyld": "",
 "echo_sacred_wylds": "",
 "echo_festival": "",
 "echo_reflection": "",
 "echo_ritual": "",
 "echo_oracle": "",
 "echo_personal_quest": "",
 "echo_personal_clue_01": "",
 "echo_tehand": "",
 "echo_personal_keepsake": "",
 "echo_chronicles_assignment": "",
 "echo_first_departure": "",
 "itharkael_free_time_started": "false",
 "itharkael_room_entered": "false",
 "itharkael_room_done": "false",
 "itharkael_room_desk_seen": "false",
 "itharkael_room_records_seen": "false",
 "itharkael_room_rest_seen": "false",
 "itharkael_room_keepsake_seen": "false",
 "personal_keepsake_id": "",
 "personal_keepsake_taken": "false",
 "personal_keepsake_popup_seen": "false",
 "itharkael_archive_entered": "false",
 "itharkael_archive_done": "false",
 "itharkael_archive_reading_seen": "false",
 "itharkael_archive_reports_seen": "false",
 "itharkael_archive_relics_seen": "false",
 "itharkael_oracle_encounter_seen": "false",
 "itharkael_courtyard_entered": "false",
 "itharkael_courtyard_done": "false",
 "itharkael_courtyard_rest_seen": "false",
 "itharkael_courtyard_seekers_seen": "false",
 "itharkael_courtyard_envoys_seen": "false",
 "itharkael_courtyard_debate_choice": "",
 "itharkael_courtyard_personal_response": "",
 "itharkael_great_hall_entered": "false",
 "quest_chronicles_status": "inactive",
 "quest_chronicles_objective": "",
 "corvus_route_hint": "",
 "portal_attunement_complete": "false"
};
purchases = {};
achievements = [];
nav.setStartingStatsClone(stats);if (achievements.length) {
  nav.loadAchievements(achievements);
}
if (nav.loadProducts) nav.loadProducts([], purchases);

isCogPublished = true;

